// import "../w3m"; // No longer needed, initialization moved to client component
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Web3ModalInitializer from "../components/Web3ModalInitializer";
import Header from "../components/Header";
import Main from "../components/Main";
import Footer from "../components/Footer";
import Web3ProviderClient from "../components/Web3ProviderClient";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-background`}
      >
        <Web3ModalInitializer />
        <Web3ProviderClient>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Web3ProviderClient>
      </body>
    </html>
  );
}
