"use client";
import { createWeb3Modal } from "@web3modal/wagmi/react";
import { defaultWagmiConfig } from "@web3modal/wagmi/react/config";
import { mainnet, bsc } from "wagmi/chains";

const projectId = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID || "demo";

export const wagmiConfig = defaultWagmiConfig({
  chains: [mainnet, bsc],
  projectId,
  metadata: {
    name: "Crypto Token Dashboard",
    description: "Generated by create next app",
    url: "http://localhost:3000",
    icons: [],
  },
});

createWeb3Modal({
  wagmiConfig,
  projectId,
  chains: [mainnet, bsc],
});
